### ISSUE TITLE
config not working as expected v5.2.0.0

### ISSUE THREAD

**Issue by Temil2006** [spikeydragoon/Cross-Ark-Chat#15]
was running with 4.1.0.0 and running fine. Updated to 5.2.0.0 and having alot of issues. I didn't use the same config, rebuild it from scratch. here are some of the issues I found and had to revert back to 4.1.0.0 as it's un-usable currently.

1. Join and Leave messages are sending to chat channel ID and to JoinLeaveNotificationsDiscordChannelID as well even though I have SendJoinLeaveNotificationsToServerOwnChannel set to true.

2. having UsePrefixToSendChat set to false still required using the prefix to send messages to in game.

3. changing UsePrefixToSendChat to true seems to work as expected, but causes duplicate messages everytime someone chats from game to discord, it comes through as 2 as it's a loop.

4. SendServerChatToOwnChannel set to false doesn't send anything to the normal channel ID setup from DiscordChannelID . setting it to true seems to send to that, instead of to the IDs defined within the config.

once i ran into all of these, I reverted back. not sure what else to try  let me know if you need my config file.

**Comment by spikeydragoon** [comment]
Yes need to see the config file since code itself is fine the stuff above is usually due to a mishap in the config.

1: When Sendjoinleavenotificationstoserverownchannel is set to true it send the messages to the servers chat channel leave it false to only send to the channel you set in the config.

2: have not seen that before unless you missing a , somewhere which is causing it to not read the useprefix properly.

3: Normally only shows up twice when you have a space in the NameTag for the server name or when accident have two instances of the bot running check the task manager to make sure.

4: SendServerChatToOwnChannel is only used when you want the servers chat to go to its own channel it still sends a copy to the main channel in the config as thats used as a all channel most admins hide that to just keep an eye on servers.

Can try those few changes above but if you send the config just make sure to delete the password and bottoken out.

**Comment by Temil2006** [comment]
[Config.zip](https://github.com/spikeydragoon/Cross-Ark-Chat/files/2867994/Config.zip)

attached is my config. I'll be honest, i don't know which of the settings I mentioned are changed in the config as this is the last copy I had, however only the values mentioned were changed to try and get it working. I removed the token and pass as you stated. let me know if you need me to try anything specific. I don't rule out that it might be a config issue on my part.. however, 2+ hrs setup and testing and redoing the config file about 10times, I just kind of ran out of ideas, lol. thanks for the wonderful program and the help to look this over.

**Comment by spikeydragoon** [comment]
Got a notification that your replied but not seeing it anymore but ill reply based on that notification in cause you still need answer.

Few things.
1: you have all your servers discord channel set to the same thing so if your wanting them to go to same location set SendServerChatToOwnChannel to false. By default with that false everything goes to the ChatDiscordChannelID channel.
2: for atlas you need to change "TribeLogTag": "Tribe", to "TribeLogTag": "Company", for tribe logs to work you also have to enable the settings in the servers startup prams of -ServerRCONOutputTribeLogs without that tag tribe logs wont show up.
3: "SendJoinLeaveNotificationsToServerOwnChannel": true only set this option to true if you want the notifications to go to the servers own channel meaning if they log into c3 it will show in the c3 discord channel since your using the same channel for everything this should be false and notifications will only go to the JoinLeaveNotificationsDiscordChannelID channel.
4: For admin commands same thing "SendAdminCommandsToOwnChannel": true should be false since your sending all servers to the same channel with this set to false admin commands will only go to the AdminCommandsDiscordChannelID channel.
5: Same for tribe logs "SendTribeLogsToOwnChannel": true should be false since you dont have any tribe channels set up with this set to false they all will go to TribeLogsDiscordChannelID channel. If you want tribes to have their own channel that should be set to true then set up a tribe in the tribe settings.

Those are the few things i see to fix any issues your having. If you already fixed this please reply to let me know and close the issue. If you still have questions feel free to keep this open or reach out to us on the discord server as you will get faster replys there.

**Comment by Temil2006** [comment]
thank you for the reply, yea i posted the file, then re-read your original message about 10times and pulled the message down so I could take another crack at the config. Based on your recent reply, that seems to have all fixed it for me. the main thing i seem to have had off is what "ToOwnChannel" means.. I was taking it as...
ToOwnChannel == send to only it's own defined channel and no others. 

but, that doesn't seem to be the case. understood what I'm about to mention would require config changes, but just want to throw this out.. wouldn't the following make more since / lack of confusion?
OnlySendAdminCommandsToAssignedChannel=True/False
OnlySendJoinLeaveNotificationsToAssignedChannel=True/False

or for that matter, what about if the ID is assigned within the ID config.. example :: AdminCommandsDiscordChannelID  .. .if it's blank, send to default channel, but if it's set to anything (not blank) then send to the set channel ID? .. 

just a thought of what would have made more since to me as a moder/scripter, but you are the programmer. not telling you what to do, just giving my feedback! . .take it or leave it :)

thanks for the assist.

**Comment by spikeydragoon** [comment]
I have thought about changing it before however most wanted to keep it the same. By default it sends everything to those set channels and when you set to send to own channel that means the servers own channel so it will send a copy of the message to that channel. All of these settings are gone over in the github wiki pages.

I may look into changing the config again in the future but for now will stay as is until i get time again to work on it.

Closing issue however if anything else comes up can re-open or create new one also cant hit us up on discord as well.
