### ISSUE TITLE
Can you change the font, color, or size of the in-game chat to something besides the bold yellow?

### ISSUE THREAD

**Issue by MinTo0831** [spikeydragoon/Cross-Ark-Chat#17]
Can you change the font, color, or size of the in-game chat to something besides the bold yellow?

When will it be fixed?

**Comment by smooreace** [comment]
You dont "fix" what isnt broke

**Comment by spikeydragoon** [comment]
As smooreace mentioned there is nothing to fix. This info is gone over in the faq and on the guides for the bot but the yellow is what ark devs hard coded the rcon server chat to show up as. They do not give an option to change it at all sadly. The second they allow this to be edited over rcon i will gladly add in support for it to be changed. 

For now the only way to change rcon color and size is by using mods or a plugin from the ark beyond api that was made by someone in the ark community.

I only support using just rcon due to it being fast and reliable unlike mods and plugins tend to be.
