### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Kostriktor** [spikeydragoon/Cross-Ark-Chat#32]
Although the bot seems to be configured correctly because It does log every message that gets sent in game and it is online on discord, it does not repeat the messages in the ds chat, and logs only (even on verbose) in the 2020-02-24_RconErrors: Object reference not set to an instance of an object.
[Config.zip](https://github.com/spikeydragoon/Cross-Ark-Chat/files/4244793/Config.zip)

**Comment by spikeydragoon** [comment]
@Kostriktor That error sometimes shows up due to a bug with arks message buffer system and the rcon lib im using. So can just ignore that for now.

Your config is good, however you need to set the ChatDiscordChanneldID to the channel you want the bot to send messages do. Currently you can not have that blank. I will be changing that in the version im working on but for now just keep it set.

Only other thing you might want to change is change the ServerTag back to "". With the way you have it now it will repeat the name when sending messages. Those tags are used for discord markdowns mostly tho some use it to change what it says.

**Comment by Kostriktor** [comment]
very useful info ! working well now ! thanks

**Comment by spikeydragoon** [comment]
np
