### ISSUE TITLE
Various noob issues

### ISSUE THREAD

**Issue by marilolli** [spikeydragoon/Cross-Ark-Chat#49]
Hi friend. Thanks for creating this software. I was able to enjoy it on another server but so far setting it up on my own has been a bit of trouble. 
I was able to finally get CrossArkChat.exe to actually stay open and stay connected with the gateway, etc. When I type into discord, the message is relayed into the crossarkchat program, however, no discord messages go into the ARK server, and no ARK chat is relayed to discord. Likewise, when I try to do any d! commands it tells me I don't have the required role even though I'm the admin of both the discord and the ARK server. 

Any help would be greatly appreciated.

**Comment by spikeydragoon** [comment]
Sorry for delay been away due to moving into new house if your still having issues just reply here or ask away in our discord server.

Normally that issue can be due to a few things. Config being wrong, space in servers name tag, and it not connecting to rcon.

Regarding the role not working make sure you setup the _discordroles.json file as that is where you set the roles up so bot knows who is allowed to do what.
