### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by TOXid** [spikeydragoon/Cross-Ark-Chat#5]
Cross-Ark-Chat not support sending Unicode characters via RCON. 
When I use this https://arkserverapi.com/threads/unicode-rcon.32/  plugin - server send normal unicode to Cross-Ark-Chat (i can see it in Cross-Ark-Chat window and Log file) but it send "????" instead unicode to other servers in cluster.

**Comment by spikeydragoon** [comment]
Thats due to ark not supporting unicode. The unicode in the ark server api only supports unicode in one direction not both. In other words it sends unicode but cant receive it.

This is quote from the unicode api dev.
"It was made to properly display messages sent from the server. I will look if it's possible to do same with receiving also."

**Comment by TOXid** [comment]
Can you add support for translitizing unicode characters to send to the server?

**Comment by spikeydragoon** [comment]
Due to how both Unicode and rcon works i will be unable to do that. The real fix would be if ark devs add it in or if the dev of ark api adds it in.

Im aware there are a few "workarounds" but they are nasty and dont work well at all. So i would rather not include it in my program since the bot itself supports Unicode so if it ever gets added you shouldnt have to do anything to see it work.

**Comment by TOXid** [comment]
Ok. I understood you. I was hoping that it was possible to create a custom "dictionary" for translitization before sending. For example. The server gets the word "медведь" by the dictionary matches the characters м=m, е=e, д=d, в=v, е=e, д=d, ь=' and sends to the server "medved'".

**Comment by spikeydragoon** [comment]
After the high request for this i have added it into new version 3.3.

I still wont build the list myself however in the wordfilter.json file there is a section called wordreplacementlist that you can add the old letter/word and bot will replace it with the the new letter/word.

This will allow the above to happen you just would build your own custom list so you would have more control over what you want replaced.
