### ISSUE TITLE
Chat not scrolling down.

### ISSUE THREAD

**Issue by TeH-BaK** [spikeydragoon/Cross-Ark-Chat#50]
I think there is a way for this to be fixed by the bot, I've noticed that the chat doesn't bug out when people are just chit chatting, lines no more than two long. but as soon as someone starts writing lots of large bodys of text, it glitches.

It therefore would be possible for the bot to edit these large bodys of text into multiple messages no more than two/three lines long at a time and avoid the issue.

I haven't been able  to calculate the exact threshold at which it does this, and thats probrably because its not monospaced text, but if you assumed all messages were written in the largest letters e.g. `m` then you could decide a limit to the chars and make more than that overflow to another message.

I would love to know your thoughts on this.

_Originally posted by @TeH-BaK in https://github.com/spikeydragoon/Cross-Ark-Chat/issues/48#issuecomment-720057740_

**Comment by spikeydragoon** [comment]
Sorry for delay been away due to moving into new house if your still having issues just reply here or ask away in our discord server.

From my testing even with just a single word if there is enough messages I was able to cause the chat to bug out. I think its just bugs after ark chat hits either a certain text amount from the serverchat command or maybe how quick the messages come in hard to say since it is kinda random.

I will be limiting the text size in future anyways to match discords text limit so i can just apply same method to the ark chat and allow it to be customized by a setting range. So if its outside of the set range or up to discords limit being the hard cap it will break it up in multi messages.

Past that its either wait for ark devs to add in a chat command to rcon, me making a mod that adds a custom chat window, or me making a plugin for the ark api that puts it as normal chat. Im thinking about adding both however it will be a while before i do that since i need to get the new setup into beta then released first before i plan other additions to it.
