### ISSUE TITLE
Do not select server when only having one

### ISSUE THREAD

**Issue by ToeiRei** [spikeydragoon/Cross-Ark-Chat#51]
I run Cross-Ark-Chat as a bridge between discord and the ark server.

When sending commands to the server like 'saveworld' the discord bot asks which server I would like to run that on - which is obvious as I just have one... Is it possible to skip that question?

**Comment by spikeydragoon** [comment]
Sorry for delay been away due to moving into new house if your still having issues just reply here or ask away in our discord server.

yes by either typing the name tag after the command or all.
Example
d!saveworld island or d!saveworld all

I have it added to notes so in new setup it will just ignore that question if there is only one server active in the config.
