### ISSUE TITLE
No settings to change frozen notifications

### ISSUE THREAD

**Issue by randycarrero** [spikeydragoon/Cross-Ark-Chat#53]
when you freeze Dinos you have no settings to remove the server, tribe id and such

**Comment by spikeydragoon** [comment]
Sorry for delay been away due to moving into new house if your still having issues just reply here or ask away in our discord server.

If your referring to the freeze under tribe logs there is option to hide those its a true/false setting in the config which should work regardless of the tribe log unless ark has changed the format for it.

If your referring to the freeze dinos rcon command then not sure what you mean.

**Comment by randycarrero** [comment]
![image](https://user-images.githubusercontent.com/15186165/100213313-75dc8080-2edc-11eb-996a-0a1e021dd94d.png)
I have the settings set up so I do not know why it only shows up when I freeze a Dino

**Comment by spikeydragoon** [comment]
Noticed it does that when it starves to death as well so they must have changed the format Ill look into fixing both of those in new setup.

**Comment by randycarrero** [comment]
Thank you very much.
