### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by remedy1** [spikeydragoon/Cross-Ark-Chat#55]
How much trouble would it be to add the ability to run a program and send the results to chat?

Context. I provide rare and high level spawn maps on my web site but maps aren't really appropriate for eggs because when people are hunting eggs, that's when they spawn. So I would like to be able to run a program that will extract egg co-ordinates on demand like when someone says "EGGS!" in global chat which would trigger the program to run (which in this case would do a world save, run the extractor, then produce coords) then send the results back to global chat.

The inputs could be as simple as a string for the program to be run and a string for the location of the results, probably a text file. Probably it should be run asynchronously so maybe a time for the expected result file to be created.

**Comment by spikeydragoon** [comment]
@remedy1 With the new setup I am working on that will not work since in future bot will be hosted by me. 
Discord has new features that will only be for large bots so having everyone self hosting will keep me from being able to provide them to everyone in case your wondering why.

I will be providing some cool features outside of just the bot though in new setup to offset the fact that self hosting in new versions wont be a thing. I will provide more information on this once we get into the beta phase.

What you can do now is add a discord bot and set it to listen to other bots. Once that bot sees the eggs command it can send request to you site.
