### ISSUE TITLE
Does this work if we are hosting with https://arkservers.io/ ?

### ISSUE THREAD

**Issue by Sonny-Crockett** [spikeydragoon/Cross-Ark-Chat#57]
Would I need to get them to add this to the server in the cloud?

**Comment by spikeydragoon** [comment]
@Sonny-Crockett If they offer that then yes however most providers will not do that. Serverblend is one of the few companys that will host the bot for you if you have a ark server with them.

Otherwise you need to host the bot on your own pc or a rented vm that runs 24/7. You can get a linux vm for $7-10 a month.  People also use everything from old laptops or rpies to self host the bot since it does not need much power to run.

To be clear this is not a ark api plugin so just putting it in the ark server folder does not make it work.

**Comment by Sonny-Crockett** [comment]
So the bot does not need to be on the server OR a PC running ark? It can be on any internet connected device?

Thanks for the help!

**Comment by spikeydragoon** [comment]
correct
