### ISSUE TITLE
Local chat being broadcasted throughout servers?

### ISSUE THREAD

**Issue by Cheeritup** [spikeydragoon/Cross-Ark-Chat#61]
Basically title, I saw one of your forums comments that mentioned someone being able to disable LOCAL from being broadcasted?

**Comment by spikeydragoon** [comment]
@Cheeritup Yes that is what I was told however when a few other users tried what the person suggested it didnt work for them. So something can cause the local chat to not show up in rcon however no one can figure it out. Its possible it was just a mod/plugin that person was using and not an ark setting.

I would just assume it always shows though since i tried a few things as well and it always seemed to show up.
