### ISSUE TITLE
Discord Bot Issue

### ISSUE THREAD

**Issue by Beenless** [spikeydragoon/Cross-Ark-Chat#62]
Hello! I followed the guide to the T and my Discord bot isn't displaying as a bot at all. It doesn't show up as online or offline in the player list on the right. Other than that the rest of the code does work.

I have contacted Discord support and they told me because its not a bot they made or maintain there's nothing they can do :C
please help, I really want this to work.

**Comment by spikeydragoon** [comment]
@Beenless If chat and everything is working only discord is not usually is one of two things.

1: Make sure your discord bot token is correct in the bots config. This is how it is able to show online/offline and connect to discord server.
2: Make sure UseDiscord is set to true at the top of the bots config.
3: After the above is done then make sure to invite the bot to the server otherwise it will not show up at all.
