### ISSUE TITLE
would someone please tell me what I'm doing wrong

### ISSUE THREAD

**Issue by nullb650** [spikeydragoon/Cross-Ark-Chat#66]

**Comment by spikeydragoon** [comment]
No information was provided so I am not sure what is wrong. Please put what is happening and I can assist.

Quickest thing would be the wiki pages as it has the steps to get the bot running.
https://github.com/spikeydragoon/Cross-Ark-Chat/wiki/Getting-started-for-windows

If bot keeps failing to open that means something is wrong with the config so make sure to check if the json format is correct.
If you are not familiar with json formatting you can use something like https://jsonlint.com/ to validate it for you.

Next thing would be to double check that the ip/admin password/ rcon ports are all correct and that the active is true for the servers you want to currently connect to.
If its saying adding to auto reconnect queue then either something is blocking the bot from connection to the server like firewall, antivirus or router so double check those.

Past that if it says its ready and not saying adding to auto reconnect queue then its likely another rcon program pulling your chat first since only one program at a time can get chat from an ark server.

**Comment by spikeydragoon** [comment]
Closing due to no reply.

Feel free to open again if still having issues.
