### ISSUE TITLE
rcon giveitemnumtoplayer cannot use

### ISSUE THREAD

**Issue by zack4488** [spikeydragoon/Cross-Ark-Chat#77]
i cannot use "giveitemnumtoplayer"

![](https://cdn.discordapp.com/attachments/1058430527788548166/1150455603186118716/image.png)

**Comment by spikeydragoon** [comment]
@zack4488  It might be bugged over rcon since I dont remember it ever working but the format you using is not right so try this first.

giveitemnumtoplayer playerId itemId quantity quality blueprint

To see the command format can always do d!help commandName and it will show you how to use it.

If that still does not work you can try putting a "" around each var like this
giveitemnumtoplayer "playerId" "itemId" "quantity" "quality" "blueprint"

**Comment by zack4488** [comment]
[image: image.png]
not working

spikeydragoon ***@***.***> 于2023年9月11日周一 01:36写道：

**Comment by zack4488** [comment]
![image](https://github.com/spikeydragoon/Cross-Ark-Chat/assets/34994511/32dfd2ee-0343-48af-91b4-9a856eac4280)

**Comment by spikeydragoon** [comment]
@zack4488 That last option should be false/true not 0/1
0 = false
1 = true

**Comment by zack4488** [comment]
It work

spikeydragoon ***@***.***> 于 2023年9月11日周一 下午10:49写道：

**Comment by spikeydragoon** [comment]
Good if you have any other problems with it feel free to reopen this or create new one if its about something else.
