### ISSUE TITLE
Ark -> Discord not working in background

### ISSUE THREAD

**Issue by Wallart** [spikeydragoon/Cross-Ark-Chat#8]
Hi @spikeydragoon great job with this tool, it's very useful !

I noticed an issue when running in background mode (nohup ./CrossArkDiscord &)
The messages are forwarded from Discord to ARK cluster, but it's not working from ARK cluster to Discord.
But when i run in foreground everything is fine.

As a temporary fix I use the screen command : https://doc.ubuntu-fr.org/screen
I am able to run CrossArk in foreground in a detachable virtual terminal

**Comment by spikeydragoon** [comment]
Not a major Linux user so that is past me however i did try running the bot use everything you said above and i let it run for a whole day on my virtual Ubuntu server and it ran without any problems in both the foreground and background.

Code wise nothing is Windows/Linux so it should run fine on both systems. The libs i use for both discord and steam are made to run on both as well. 

So if you have any ideas on what it might be or a better way to run it on Linux let me know and ill look into it and update the Linux portion of the guide.
