### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Rockinpacha** [spikeydragoon/Cross-Ark-Chat#83]
Hello, chat was working fine however now wont connect on all 3 servers. I have attached the config file

**Comment by spikeydragoon** [comment]
@Rockinpacha  If that is your real password make sure to change it. I removed the config from your post to prevent anyone else from seeing it.

Only issue I see is after each server "Active": true, remove the , since in json the last value in the list does not get a ,
once edited it should be just "Active": true

**Comment by Rockinpacha** [comment]
oops thanks for pointing that out 

I actually added the , after true today to see if it would help but it didn't. Will revert back to no ,

Strangely after leaving the chat to run for a while it suddenly connect to all servers

**Comment by spikeydragoon** [comment]
Closing since sounds like your good now. If it still has issues can just reopen this ticket or create new one if its a different problem.
