### ISSUE TITLE
Local Ark Chat

### ISSUE THREAD

**Issue by itdirector3** [spikeydragoon/Cross-Ark-Chat#9]
Is is possible to disable the local Ark chat from showing up in both Discord and Cross Ark?

Thanks

**Comment by spikeydragoon** [comment]
There is no way to filter local out as it just gives all messages when running the getchat command that you use in rcon to get messages. I think there is a setting server side where you can disable it since i have heard a few say that local chat doesn't show in their chat however im not sure what they changed in the servers inis.
